ci: update pr code warning workflow to exclude test files and check console.debug
Signed-off-by: Wanjin Noh <wanjin@megazone.com>

diff --git a/.github/workflows/pull_request_code_warning.yml b/.github/workflows/pull_request_code_warning.yml
--- a/.github/workflows/pull_request_code_warning.yml
+++ b/.github/workflows/pull_request_code_warning.yml
@@ -16,7 +16,6 @@ on:
       - '**/.lintstagedrc.js'
       - '**/*.md'
       - '**/*.env'
-      - '**/__tests__/**/*.test.ts'
     branches:
       - master
       - feature-*
@@ -28,6 +27,8 @@ jobs:
     runs-on: ubuntu-latest
     env:
       NODE_ENV: 'development'
+      EXCLUDE_DIRS_TODO: '{node_modules,.github,.git,**/__tests__/**/*.test.ts}'
+      EXCLUDE_DIRS_LOG: '{node_modules,.git,**/vite.config.js,packages/mirinae/scripts/**,packages/mirinae/cli/**,apps/web/public/lottie.js,apps/web/build}'
 
     steps:
       - name: Checkout code
@@ -37,7 +38,7 @@ jobs:
         id: check_todo
         run: |
           echo "Checking for TODOs..."
-          TODO_FILES=$(grep -rl "TODO" apps/web/src --exclude-dir={node_modules,.github} || true)
+          TODO_FILES=$(grep -rl "// TODO" apps/web/src --exclude-dir=$EXCLUDE_DIRS_TODO || true)
           TODO_COUNT=0
           if [ -n "$TODO_FILES" ]; then
             echo "The following files contain TODO:"
@@ -53,7 +54,7 @@ jobs:
         id: check_console_log
         run: |
           echo "Checking for console.log..."
-          LOG_FILES=$(grep -rl "console.log" . --exclude-dir={node_modules,.git} || true)
+          LOG_FILES=$(grep -rl "console.log" . --exclude-dir=$EXCLUDE_DIRS_LOG || true)
           LOG_COUNT=0
           if [ -n "$LOG_FILES" ]; then
             echo "The following files contain console.log:"
@@ -65,12 +66,29 @@ jobs:
           echo "::warning:: Found $LOG_COUNT file(s) with console.log."
           echo "console_log_count=$LOG_COUNT" >> $GITHUB_ENV
 
+      - name: Check for console.debug
+        id: check_console_debug
+        run: |
+          echo "Checking for console.debug..."
+          LOG_FILES=$(grep -rl "console.debug" . --exclude-dir=$EXCLUDE_DIRS_LOG || true)
+          LOG_COUNT=0
+          if [ -n "$LOG_FILES" ]; then
+            echo "The following files contain console.debug:"
+            echo "$LOG_FILES"
+            LOG_COUNT=$(echo "$LOG_FILES" | wc -l)
+          else
+            echo "No console.debug found."
+          fi
+          echo "::warning:: Found $LOG_COUNT file(s) with console.debug."
+          echo "console_debug_count=$LOG_COUNT" >> $GITHUB_ENV
+
       - name: Fail if issues found
         run: |
           echo "TODO Count: $todo_count"
           echo "console.log Count: $console_log_count"
+          echo "console.debug Count: $console_debug_count"
           if [ "$todo_count" -gt 0 ]; then
-            echo "::warning:: Workflow failed. TODO count: $todo_count, console.log count: $console_log_count"
+            echo "::warning:: Workflow failed. TODO count: $todo_count, console.log count: $console_log_count, console.debug count: $console_debug_count"
             exit 1
           else
             echo "No issues found. Workflow passed."
