fix: fail!
Signed-off-by: yuda <yuda@megazone.com>

diff --git a/.github/workflows/pull_request_code_warning.yml b/.github/workflows/pull_request_code_warning.yml
--- a/.github/workflows/pull_request_code_warning.yml
+++ b/.github/workflows/pull_request_code_warning.yml
@@ -64,12 +64,13 @@ jobs:
           echo "::warning Found $LOG_COUNT file(s) with console.log."
           echo "console_log_count=$LOG_COUNT" >> $GITHUB_ENV
 
-      - name: End with warning if issues found
+      - name: Fail if issues found
         run: |
           echo "TODO Count: $todo_count"
           echo "console.log Count: $console_log_count"
           if [ "$todo_count" -gt 0 ] || [ "$console_log_count" -gt 0 ]; then
-            echo "::warning::Workflow completed with issues. TODO count: $todo_count, console.log count: $console_log_count"
+            echo "::warning Workflow failed. TODO count: $todo_count, console.log count: $console_log_count"
+            exit 1
           else
             echo "No issues found. Workflow passed."
           fi
